let db, session, current=null;
const $=s=>document.querySelector(s), money=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10), eligibleDate=d=>new Date(d)>=new Date('2026-08-19');
function toast(t){$('#toast').textContent=t;$('#toast').className='show';setTimeout(()=>$('#toast').className='',2200)}
function blankRow(){return{id:crypto.randomUUID(),packets:'',consignor:'',consignorPhone:'',consignee:'',consigneePhone:'',weight:'',amount:0,cnNo:'',status:'PENDING',payment:'PENDING',delivery:'DOOR DELIVERY',paymentLocation:'TATA',pods:[],waConsignor:false,waConsignee:false,onAccount:false}}
function cashRow(r){return !r.onAccount&&r.payment!=='MONTHLY'&&r.paymentLocation!=='HOWRAH'}
function paidAmount(r){return r.payment==='PAID'&&r.paymentLocation==='HOWRAH'?0:Number(r.amount||0)}
async function persist(){await window.mcs.save(db)}
async function login(){const id=$('#uid').value.trim().toLowerCase(),p=$('#pwd').value;if(!db.settings.admin&&id==='admin'){if(p.length<6)return toast('PASSWORD MINIMUM 6 CHARACTERS');db.settings.admin=p;await persist();toast('ADMIN PASSWORD CREATED')}const map={admin:db.settings.admin,howrah:db.settings.howrah,tata:db.settings.tata};if(!map[id]||map[id]!==p)return toast('WRONG LOGIN');session={id,admin:id==='admin'};$('#login').hidden=true;$('#app').hidden=false;dashboard()}
function dashboard(){current=null;$('#editor').hidden=true;$('#dashboard').hidden=false;const charts=[...db.charts].sort((a,b)=>b.date.localeCompare(a.date));$('#chartCount').textContent=`${charts.length} CHARTS`;$('#rowCount').textContent=`${charts.reduce((n,c)=>n+c.rows.length,0)} ROWS`;$('#podCount').textContent=`${charts.reduce((n,c)=>n+c.rows.reduce((x,r)=>x+(r.pods||[]).length,0),0)} POD`;
 $('#chartList').innerHTML=charts.map(c=>`<article><h3>${c.no}</h3><b>${c.date} • ${c.route}</b><p>${c.vehicle||'VEHICLE NOT ENTERED'} • ${c.rows.length} ROWS</p><span>${money(c.rows.filter(cashRow).reduce((n,r)=>n+Number(r.amount||0),0))} CASH</span><button data-open="${c.id}">OPEN CHART</button></article>`).join('')||'<p class="empty">NO CHART — CLICK + NEW CHART</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openChart(b.dataset.open));renderCash()}
function renderCash(){const cs=db.charts.filter(c=>eligibleDate(c.date));const total=cs.reduce((n,c)=>n+c.rows.filter(cashRow).reduce((x,r)=>x+Number(r.amount||0),0),0),hand=db.handovers.reduce((n,h)=>n+Number(h.amount||0),0);$('#cashBalance').textContent=money(Math.max(0,total-hand));$('#cashAlert').classList.toggle('clear',total-hand<=0)}
function openChart(id){current=db.charts.find(c=>c.id===id);if(!current)return;$('#dashboard').hidden=true;$('#editor').hidden=false;$('#chartNo').value=current.no;$('#chartDate').value=current.date;$('#route').value=current.route;$('#vehicle').value=current.vehicle||'';$('#driver').value=current.driver||'';$('#driverPhone').value=current.driverPhone||'';$('#packets').value=current.dispatchedPackets||'';renderRows()}
function newChart(){const d=today(),route=session.id==='tata'?'TATA TO HOWRAH':'HOWRAH TO TATA';current={id:crypto.randomUUID(),no:`${route.startsWith('TATA')?'T':'H'}${d.slice(-2)}A`,date:d,route,vehicle:'',driver:'',driverPhone:'',dispatchedPackets:'',rows:[blankRow()]};db.charts.push(current);openChart(current.id)}
function field(r,k,type='input',opts=''){const val=k==='amount'?Number(r[k]||0):r[k]||'';return type==='select'?`<select data-id="${r.id}" data-k="${k}">${opts.split('|').map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select>`:`<input data-id="${r.id}" data-k="${k}" ${k.includes('Phone')?'inputmode="numeric"':''} ${k==='amount'?'type="number"':''} value="${String(val).replace(/"/g,'&quot;')}">`}
function renderRows(){const groups=[['DOOR DELIVERY / ON ACCOUNT',r=>r.onAccount||r.payment==='MONTHLY'],['CASH COLLECTION - DOOR DELIVERY',r=>cashRow(r)&&r.delivery!=='GODOWN DELIVERY'],['CASH COLLECTION - GODOWN DELIVERY',r=>cashRow(r)&&r.delivery==='GODOWN DELIVERY']];let html='';for(const [name,test] of groups){const rows=current.rows.filter(test);if(!rows.length)continue;html+=`<tr class="section"><td colspan="12">${name}</td></tr>`;for(const r of rows)html+=rowHtml(r)}const leftovers=current.rows.filter(r=>!groups.some(g=>g[1](r)));if(leftovers.length){html+=`<tr class="section"><td colspan="12">NEW / UNCLASSIFIED</td></tr>`;html+=leftovers.map(rowHtml).join('')}$('#rows').innerHTML=html;document.querySelectorAll('[data-id][data-k]').forEach(x=>x.onchange=()=>{const r=current.rows.find(r=>r.id===x.dataset.id),k=x.dataset.k;r[k]=k==='amount'?Number(x.value):x.value;if(k==='payment')r.onAccount=x.value==='MONTHLY';renderRows()});document.querySelectorAll('[data-pod]').forEach(x=>x.onclick=()=>addPod(x.dataset.pod));document.querySelectorAll('[data-wa]').forEach(x=>x.onclick=()=>sendWa(x.dataset.wa,x.dataset.who));document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{current.rows=current.rows.filter(r=>r.id!==x.dataset.del);renderRows()});document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>window.mcs.openFile(x.dataset.view))}
function rowHtml(r){const amount=r.payment==='PAID'&&r.paymentLocation==='HOWRAH'?'<b class="zero">₹0.00</b>':field(r,'amount');const pod=(r.pods||[]).map((p,i)=>`<button data-view="${p}">POD ${i+1}</button>`).join('');return`<tr><td>${field(r,'packets')}</td><td>${field(r,'consignor')}${field(r,'consignorPhone')}</td><td>${field(r,'consignee')}${field(r,'consigneePhone')}</td><td>${field(r,'weight')}</td><td>${amount}</td><td>${field(r,'cnNo')}</td><td>${field(r,'status','select','PENDING|OUT FOR DELIVERY|POD RECEIVED')}</td><td>${field(r,'payment','select','PENDING|PAID|MONTHLY')}</td><td>${field(r,'delivery','select','DOOR DELIVERY|GODOWN DELIVERY|URGENT DELIVERY')}</td><td>${field(r,'paymentLocation','select','TATA|HOWRAH')}</td><td><button data-pod="${r.id}">UPLOAD POD</button>${pod}<button data-wa="${r.id}" data-who="consignor">WA CONSIGNOR ${r.waConsignor?'✓':'PENDING'}</button><button data-wa="${r.id}" data-who="consignee">WA CONSIGNEE ${r.waConsignee?'✓':'PENDING'}</button></td><td><button class="danger" data-del="${r.id}">×</button></td></tr>`}
async function addPod(id){const r=current.rows.find(r=>r.id===id),files=await window.mcs.addPod(r.cnNo);if(files.length){r.pods=[...(r.pods||[]),...files];r.status='POD RECEIVED';await persist();renderRows();toast('POD SAVED')}}
async function sendWa(id,who){const r=current.rows.find(r=>r.id===id),phone=r[who+'Phone'];if(!phone)return toast('WHATSAPP NUMBER NOT ENTERED');await window.mcs.whatsapp({phone,message:`CN ${r.cnNo} - Please keep this POD for further payment issue raised from particular company.`});r[who==='consignor'?'waConsignor':'waConsignee']=true;await persist();renderRows()}
async function saveChart(){Object.assign(current,{no:$('#chartNo').value,date:$('#chartDate').value,route:$('#route').value,vehicle:$('#vehicle').value,driver:$('#driver').value,driverPhone:$('#driverPhone').value,dispatchedPackets:$('#packets').value});for(const r of current.rows){for(const n of [r.consignor,r.consignee])if(n)db.parties[n]=(n===r.consignor?r.consignorPhone:r.consigneePhone)||db.parties[n]||''}await persist();toast('COMPLETE CHART SAVED');dashboard()}
function cashLedger(){const dates=[...new Set(db.charts.filter(c=>eligibleDate(c.date)).map(c=>c.date).concat(db.handovers.map(h=>h.date)))].sort().reverse();let total=0,hand=0;$('#cashLedger').innerHTML=dates.map(d=>{const day=db.charts.filter(c=>c.date===d),t2h=day.filter(c=>c.route==='TATA TO HOWRAH').reduce((n,c)=>n+c.rows.filter(cashRow).reduce((x,r)=>x+Number(r.amount||0),0),0),h2t=day.filter(c=>c.route==='HOWRAH TO TATA').reduce((n,c)=>n+c.rows.filter(cashRow).reduce((x,r)=>x+Number(r.amount||0),0),0),hs=db.handovers.filter(h=>h.date===d);total+=t2h+h2t;hand+=hs.reduce((n,h)=>n+Number(h.amount||0),0);return`<article><h3>${d}</h3><p><b>TATA → HOWRAH</b><strong>${money(t2h)}</strong></p><p><b>HOWRAH → TATA</b><strong>${money(h2t)}</strong></p><p><b>DATE TOTAL</b><strong>${money(t2h+h2t)}</strong></p>${hs.map(h=>`<p class="handover"><b>HANDOVER ${h.date} • TO: ${h.to}</b><strong>− ${money(h.amount)}</strong></p>`).join('')||'<p>NO HANDOVER</p>'}<h4>BALANCE AFTER DATE: ${money(total-hand)}</h4></article>`}).join('')||'<p>NO CASH DATA FROM 19/08/2026</p>';$('#cashGrand').innerHTML=`TOTAL ${money(total)} − HANDOVER ${money(hand)} = BALANCE ${money(total-hand)}`;$('#cashDialog').showModal()}
$('#loginBtn').onclick=login;$('#pwd').onkeydown=e=>{if(e.key==='Enter')login()};$('#logoutBtn').onclick=()=>location.reload();$('#homeBtn').onclick=dashboard;$('#backBtn').onclick=dashboard;$('#newBtn').onclick=newChart;$('#addRow').onclick=()=>{current.rows.push(blankRow());renderRows()};$('#saveChart').onclick=saveChart;$('#deleteChart').onclick=async()=>{if(confirm('DELETE COMPLETE CHART?')){db.charts=db.charts.filter(c=>c.id!==current.id);await persist();dashboard()}};$('#cashAlert').onclick=cashLedger;$('#handoverBtn').onclick=()=>{$('#handoverDate').value=today();$('#handoverDialog').showModal()};$('#saveHandover').onclick=async()=>{const amount=Number($('#handoverAmount').value),to=$('#handoverTo').value.trim();if(!amount||!to)return toast('ENTER AMOUNT AND RECEIVER');db.handovers.push({id:crypto.randomUUID(),date:$('#handoverDate').value,amount,to});await persist();$('#handoverDialog').close();renderCash();toast('HANDOVER SAVED')};document.querySelectorAll('dialog .close').forEach(x=>x.onclick=()=>x.closest('dialog').close());$('#folderBtn').onclick=()=>window.mcs.dataFolder();$('#backupBtn').onclick=async()=>{if(await window.mcs.backup())toast('BACKUP SAVED')};$('#restoreBtn').onclick=async()=>{if(await window.mcs.restore()){db=await window.mcs.get();dashboard();toast('BACKUP RESTORED')}};
window.mcs.get().then(x=>db=x);
